programming_languages = [
    # Original languages
    {
        "name": "Python",
        "year_created": 1991,
        "creator": "Guido van Rossum",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "JavaScript",
        "year_created": 1995,
        "creator": "Brendan Eich",
        "paradigm": "Event-driven",
    },
    {
        "name": "Java",
        "year_created": 1995,
        "creator": "James Gosling",
        "paradigm": "Object-oriented",
    },
    {
        "name": "C#",
        "year_created": 2000,
        "creator": "Microsoft",
        "paradigm": "Multi-paradigm",
    },
    {"name": "Go", "year_created": 2009, "creator": "Google", "paradigm": "Concurrent"},
    {
        "name": "Rust",
        "year_created": 2010,
        "creator": "Mozilla",
        "paradigm": "Multi-paradigm",
    },
    # Classic/Historical languages
    {
        "name": "Fortran",
        "year_created": 1957,
        "creator": "John Backus",
        "paradigm": "Procedural",
    },
    {
        "name": "Lisp",
        "year_created": 1958,
        "creator": "John McCarthy",
        "paradigm": "Functional",
    },
    {
        "name": "COBOL",
        "year_created": 1959,
        "creator": "Grace Hopper",
        "paradigm": "Procedural",
    },
    {
        "name": "BASIC",
        "year_created": 1964,
        "creator": "John Kemeny and Thomas Kurtz",
        "paradigm": "Procedural",
    },
    {
        "name": "Pascal",
        "year_created": 1970,
        "creator": "Niklaus Wirth",
        "paradigm": "Procedural",
    },
    {
        "name": "C",
        "year_created": 1972,
        "creator": "Dennis Ritchie",
        "paradigm": "Procedural",
    },
    {
        "name": "Scheme",
        "year_created": 1975,
        "creator": "Guy Steele and Gerald Sussman",
        "paradigm": "Functional",
    },
    {
        "name": "SQL",
        "year_created": 1978,
        "creator": "Donald Chamberlin and Raymond Boyce",
        "paradigm": "Declarative",
    },
    {
        "name": "Ada",
        "year_created": 1980,
        "creator": "Jean Ichbiah",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "C++",
        "year_created": 1985,
        "creator": "Bjarne Stroustrup",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Perl",
        "year_created": 1987,
        "creator": "Larry Wall",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Tcl",
        "year_created": 1988,
        "creator": "John Ousterhout",
        "paradigm": "Event-driven",
    },
    {
        "name": "Haskell",
        "year_created": 1990,
        "creator": "Simon Peyton Jones",
        "paradigm": "Functional",
    },
    # 90s languages
    {
        "name": "Visual Basic",
        "year_created": 1991,
        "creator": "Microsoft",
        "paradigm": "Event-driven",
    },
    {
        "name": "Lua",
        "year_created": 1993,
        "creator": "Roberto Ierusalimschy",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "R",
        "year_created": 1993,
        "creator": "Ross Ihaka and Robert Gentleman",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Ruby",
        "year_created": 1995,
        "creator": "Yukihiro Matsumoto",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "PHP",
        "year_created": 1995,
        "creator": "Rasmus Lerdorf",
        "paradigm": "Scripting",
    },
    {
        "name": "Delphi",
        "year_created": 1995,
        "creator": "Borland",
        "paradigm": "Object-oriented",
    },
    {
        "name": "OCaml",
        "year_created": 1996,
        "creator": "INRIA",
        "paradigm": "Functional",
    },
    {
        "name": "REXX",
        "year_created": 1979,
        "creator": "IBM",
        "paradigm": "Scripting",
    },
    {
        "name": "Erlang",
        "year_created": 1986,
        "creator": "Ericsson",
        "paradigm": "Concurrent",
    },
    {
        "name": "ABAP",
        "year_created": 1983,
        "creator": "SAP",
        "paradigm": "Procedural",
    },
    {
        "name": "D",
        "year_created": 1999,
        "creator": "Digital Mars",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "ActionScript",
        "year_created": 1998,
        "creator": "Macromedia",
        "paradigm": "Event-driven",
    },
    # 2000s languages
    {
        "name": "Groovy",
        "year_created": 2003,
        "creator": "James Strachan",
        "paradigm": "Object-oriented",
    },
    {
        "name": "Scala",
        "year_created": 2004,
        "creator": "Martin Odersky",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "F#",
        "year_created": 2005,
        "creator": "Microsoft",
        "paradigm": "Functional",
    },
    {
        "name": "PowerShell",
        "year_created": 2006,
        "creator": "Microsoft",
        "paradigm": "Scripting",
    },
    {
        "name": "Clojure",
        "year_created": 2007,
        "creator": "Rich Hickey",
        "paradigm": "Functional",
    },
    # 2010s languages
    {
        "name": "Kotlin",
        "year_created": 2011,
        "creator": "JetBrains",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Dart",
        "year_created": 2011,
        "creator": "Google",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Elixir",
        "year_created": 2011,
        "creator": "José Valim",
        "paradigm": "Functional",
    },
    {
        "name": "TypeScript",
        "year_created": 2012,
        "creator": "Microsoft",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Julia",
        "year_created": 2012,
        "creator": "Jeff Bezanson et al.",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Swift",
        "year_created": 2014,
        "creator": "Apple",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Crystal",
        "year_created": 2014,
        "creator": "Ary Borenszweig",
        "paradigm": "Object-oriented",
    },
    {
        "name": "Zig",
        "year_created": 2016,
        "creator": "Andrew Kelley",
        "paradigm": "Procedural",
    },
    {
        "name": "Nim",
        "year_created": 2008,
        "creator": "Andreas Rumpf",
        "paradigm": "Multi-paradigm",
    },
    # Esoteric/niche languages
    {
        "name": "Brainfuck",
        "year_created": 1993,
        "creator": "Urban Müller",
        "paradigm": "Esoteric",
    },
    {
        "name": "Whitespace",
        "year_created": 2003,
        "creator": "Edwin Brady and Chris Morris",
        "paradigm": "Esoteric",
    },
    {
        "name": "Malbolge",
        "year_created": 1998,
        "creator": "Ben Olmstead",
        "paradigm": "Esoteric",
    },
    # Domain-specific languages
    {
        "name": "MATLAB",
        "year_created": 1984,
        "creator": "MathWorks",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "SAS",
        "year_created": 1966,
        "creator": "SAS Institute",
        "paradigm": "Procedural",
    },
    {
        "name": "Stata",
        "year_created": 1985,
        "creator": "StataCorp",
        "paradigm": "Statistical",
    },
    {
        "name": "Verilog",
        "year_created": 1984,
        "creator": "Gateway Design Automation",
        "paradigm": "Hardware description",
    },
    {
        "name": "VHDL",
        "year_created": 1980,
        "creator": "DoD",
        "paradigm": "Hardware description",
    },
    {
        "name": "GAMS",
        "year_created": 1987,
        "creator": "GAMS Development Corp",
        "paradigm": "Mathematical optimization",
    },
    {
        "name": "Prolog",
        "year_created": 1972,
        "creator": "Alain Colmerauer",
        "paradigm": "Logic",
    },
    # Web/development specific
    {
        "name": "HTML",
        "year_created": 1993,
        "creator": "Tim Berners-Lee",
        "paradigm": "Markup",
    },
    {
        "name": "CSS",
        "year_created": 1996,
        "creator": "W3C",
        "paradigm": "Stylesheet",
    },
    {
        "name": "XML",
        "year_created": 1996,
        "creator": "W3C",
        "paradigm": "Markup",
    },
    {
        "name": "JSON",
        "year_created": 2001,
        "creator": "Douglas Crockford",
        "paradigm": "Data interchange",
    },
    {
        "name": "YAML",
        "year_created": 2001,
        "creator": "Clark Evans",
        "paradigm": "Data serialization",
    },
    # Educational
    {
        "name": "Scratch",
        "year_created": 2003,
        "creator": "MIT Media Lab",
        "paradigm": "Visual",
    },
    {
        "name": "Logo",
        "year_created": 1967,
        "creator": "Wally Feurzeig",
        "paradigm": "Educational",
    },
    {
        "name": "Alice",
        "year_created": 1998,
        "creator": "Carnegie Mellon",
        "paradigm": "Educational",
    },
    # Add more obscure/interesting ones
    {
        "name": "Forth",
        "year_created": 1970,
        "creator": "Charles H. Moore",
        "paradigm": "Procedural",
    },
    {
        "name": "Smalltalk",
        "year_created": 1972,
        "creator": "Alan Kay",
        "paradigm": "Object-oriented",
    },
    {
        "name": "ML",
        "year_created": 1973,
        "creator": "Robin Milner",
        "paradigm": "Functional",
    },
    {
        "name": "Simula",
        "year_created": 1967,
        "creator": "Ole-Johan Dahl",
        "paradigm": "Object-oriented",
    },
    {
        "name": "ALGOL",
        "year_created": 1958,
        "creator": "International committee",
        "paradigm": "Procedural",
    },
    {
        "name": "B",
        "year_created": 1969,
        "creator": "Ken Thompson",
        "paradigm": "Procedural",
    },
    {
        "name": "BCPL",
        "year_created": 1967,
        "creator": "Martin Richards",
        "paradigm": "Procedural",
    },
    {
        "name": "PL/I",
        "year_created": 1964,
        "creator": "IBM",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "APL",
        "year_created": 1964,
        "creator": "Kenneth Iverson",
        "paradigm": "Array-oriented",
    },
    {
        "name": "SNOBOL",
        "year_created": 1962,
        "creator": "David Farber",
        "paradigm": "String-processing",
    },
    {
        "name": "Objective-C",
        "year_created": 1984,
        "creator": "Brad Cox",
        "paradigm": "Object-oriented",
    },
    {
        "name": "Vala",
        "year_created": 2006,
        "creator": "Jürg Billeter",
        "paradigm": "Object-oriented",
    },
    {
        "name": "Haxe",
        "year_created": 2005,
        "creator": "Nicolas Cannasse",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Red",
        "year_created": 2011,
        "creator": "Nenad Rakocevic",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Racket",
        "year_created": 1995,
        "creator": "Matthias Felleisen",
        "paradigm": "Functional",
    },
    {
        "name": "Elm",
        "year_created": 2012,
        "creator": "Evan Czaplicki",
        "paradigm": "Functional",
    },
    {
        "name": "PureScript",
        "year_created": 2013,
        "creator": "Phil Freeman",
        "paradigm": "Functional",
    },
    {
        "name": "ReasonML",
        "year_created": 2016,
        "creator": "Jordan Walke",
        "paradigm": "Functional",
    },
    {
        "name": "V",
        "year_created": 2019,
        "creator": "Alexander Medvednikov",
        "paradigm": "Multi-paradigm",
    },
    {
        "name": "Carbon",
        "year_created": 2022,
        "creator": "Google",
        "paradigm": "Multi-paradigm",
    },
]
